apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoschedule-scheduler
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoschedule-scheduler
  template:
    metadata:
      labels:
        app: autoschedule-scheduler
    spec:
      containers:
        - name: scheduler
          image: ghcr.io/justgu1/autoschedule-backend:latest
          command: ['php', 'bin/scheduler.php']
          env:
            - name: APP_ENV
              value: production
            - name: APP_DEBUG
              value: 'false'
            - name: APP_TIMEZONE
              value: America/Sao_Paulo

            - name: DB_DRIVER
              value: pgsql
            - name: DB_HOST
              value: postgresql.shared.svc.cluster.local
            - name: DB_PORT
              value: '5432'
            - name: DB_DATABASE
              value: autoschedule
            - name: DB_USERNAME
              value: autoschedule
            - name: DB_APP_USERNAME
              value: autoschedule_app
            - name: DB_PASSWORD
              valueFrom: { secretKeyRef: { name: autoschedule-secrets, key: DB_PASSWORD } }
            - name: DB_APP_PASSWORD
              valueFrom: { secretKeyRef: { name: autoschedule-secrets, key: DB_APP_PASSWORD } }

            - name: REDIS_HOST
              value: redis-master.shared.svc.cluster.local
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_PREFIX
              value: autoschedule_
            - name: REDIS_USERNAME
              value: autoschedule
            - name: REDIS_PASSWORD
              valueFrom: { secretKeyRef: { name: autoschedule-secrets, key: REDIS_PASSWORD } }

            - name: MAIL_FROM
              value: support@justgui.dev
            - name: FRONTEND_URL
              value: https://autoschedule.justgui.dev
            - name: MAIL_DSN
              valueFrom: { secretKeyRef: { name: autoschedule-secrets, key: MAIL_DSN } }

            - name: S3_ENDPOINT
              value: http://minio.shared.svc.cluster.local:9000
            - name: S3_BUCKET
              value: autoschedule
            - name: S3_REGION
              value: us-east-1
            - name: S3_PUBLIC_URL
              value: https://autoschedule.justgui.dev/cdn/autoschedule
            - name: S3_ACCESS_KEY
              valueFrom: { secretKeyRef: { name: autoschedule-secrets, key: S3_ACCESS_KEY } }
            - name: S3_SECRET_KEY
              valueFrom: { secretKeyRef: { name: autoschedule-secrets, key: S3_SECRET_KEY } }
            - name: TEMP_STORAGE_PATH
              value: /var/www/html/storage/tmp
